UI_BASE_URL = "https://www.chitai-gorod.ru/"
API_URL = "https://web-gate.chitai-gorod.ru/"
API_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzczNjI3NjcsImlhdCI6MTczNzE5NDc2NywiaXNzIjoiL2FwaS92MS9hdXRoL2Fub255bW91cyIsInN1YiI6ImU5MTEzMzZmMmI2MmMxZjJmNDhmNTkyZmY4ZmE5Yjc2NjRiMTA5Mjc2ZmIyNDc5ZWUzNzM0MmVjMTFiZjBjMzUiLCJ0eXBlIjoxMH0.lmfjzP-cpjbPrOFXDwpApmRH9ZRXebd4tfOW-6IvoO8"